### ISSUE TITLE
Repo vide ? 

### ISSUE THREAD

**Issue by CindyDelabriere** [jre-formation/jrechet-2022-Java#1]
Bonjour, 

J'ai suivi ta formation java du 20 au 24 juin à l'ENI service et tu nous a dis que tu nous mettrais à dispo dans ton repo tous les cours que tu nous a présenté et le code réalisé pendant la semaine.
Je vois que c'est toujours vide....un oubli ? (désolée de passer par ce moyen mais je n'ai pas ton mail !)

Merci

Cindy

**Comment by jrechet** [comment]
Hello,
Oui en effet j’ai oublié, autant pour moi :)
je fais ça dans le week-end !
Bon week-end,
Jérémy

Le 1 juil. 2022 à 15:22, CindyDelabriere ***@***.***> a écrit :

﻿

Bonjour,

J'ai suivi ta formation java du 20 au 24 juin à l'ENI service et tu nous a dis que tu nous mettrais à dispo dans ton repo tous les cours que tu nous a présenté et le code réalisé pendant la semaine.
Je vois que c'est toujours vide....un oubli ? (désolée de passer par ce moyen mais je n'ai pas ton mail !)

Merci

Cindy

**Comment by CindyDelabriere** [comment]
Bonjour et merci !
